_base_: '../_base_/cityscapes.yml'

model:
  type: ENCNet
  backbone:
    type: ResNet101_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_codes: 32
  mid_channels: 512 
  up_scale: 8
  in_index: [1, 2, 3]
  use_se_loss: True
  add_lateral: False

optimizer:
  type: sgd
  weight_decay: 0.0005

loss:
  types:
    - type: CrossEntropyLoss # output
    - type: CrossEntropyLoss # fcn out
    - type: SeCrossEntropyLoss # se out
      num_classes: 19
  coef: [1, 0.4, 0.2]

batch_size: 4
iters: 60000

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.1
  end_lr: 0.0001
  power: 0.9
