batch_size: 4
iters: 50

train_dataset:
  type: Dataset
  dataset_root: test_tipc/data/mini_supervisely
  train_path: test_tipc/data/mini_supervisely/train.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: test_tipc/data/mini_supervisely
  val_path: test_tipc/data/mini_supervisely/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [192, 192]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.05
  end_lr: 0
  power: 0.9

model:
  type: ENCNet
  backbone:
    type: ResNet101_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
  num_codes: 32
  mid_channels: 512 
  up_scale: 8
  in_index: [1, 2, 3]
  use_se_loss: True
  add_lateral: True


loss:
  types:
    - type: CrossEntropyLoss # output
    - type: CrossEntropyLoss # fcn out
    - type: SeCrossEntropyLoss # se out
      num_classes: 2
  coef: [1, 0.4, 0.2]
